### ISSUE TITLE
weird fd error with cd

### ISSUE THREAD

**Issue by BenjaminHThomas** [Haliris/minishell#122]
![image](https://github.com/user-attachments/assets/327f3c29-0028-4c46-bffe-8cc1a48acddd)

![image](https://github.com/user-attachments/assets/b416d6f1-d291-4090-b637-6cc0e59353e0)

**Comment by Haliris** [comment]
I cannot reproduce on wsl, need to test at school, but this trends towards a quirk of fedora imo

**Comment by BenjaminHThomas** [comment]
thanks fedora, very cool. Non-issue
