### ISSUE TITLE
Heredoc Path not valid after cd

### ISSUE THREAD

**Issue by BenjaminHThomas** [Haliris/minishell#16]
Need to have the heredoc parser have the absolute path, rather than the relative path. 

When we're doing the cleanup at exit time we need to remove the heredoc file, which is tricky if we've cd'd into another directory.

**Comment by nyzss** [comment]
LGTM :+1:

**Comment by Haliris** [comment]
Need to modify create_here_doc to call str_rejoin and merge the return value of getcwd() with the heredoc->path string and then go on from there.

**Comment by BenjaminHThomas** [comment]
non-issue
