### ISSUE TITLE
Double and single quotes parsing behavior diffs

### ISSUE THREAD

**Issue by Haliris** [Haliris/minishell#33]
![image](https://github.com/user-attachments/assets/a5985665-19b6-4659-8409-16417c84db89)
vs
![image](https://github.com/user-attachments/assets/c6f9ba37-7641-46f8-b60b-1adad6d83ef5)
/////////////////////////////////////////////////////
![image](https://github.com/user-attachments/assets/6a21946e-6fee-49e2-9fbb-9d1748b07eb2)
vs
![image](https://github.com/user-attachments/assets/3b23e388-7d9c-4bec-a3bd-d3921633c158)
/////////////////////////////////////////////////
![image](https://github.com/user-attachments/assets/d3f20e83-7736-4e53-b827-77b94a060741)
vs
![image](https://github.com/user-attachments/assets/701291b8-e3d3-4859-bb23-287656d853d1)

**Comment by Haliris** [comment]
Most likely has to do with the if statement on line 68 in lexer.c

**Comment by Haliris** [comment]
![image](https://github.com/user-attachments/assets/451a3fb6-99c6-427b-b483-3fe84cedbafc)
It can't parse this correctly

**Comment by Haliris** [comment]
For the case of  `""ls""`:

The issue lies with how skip_invalid_chars() is called, it will accurately skip quotes at loop entry in build_tokenlist1, but the second call in build_tokenlist2 does nothing as the pointer offset will always be pointing at either a valid character or nothing at all. 

currently the get_.._tk functions all presume that they receive valid strings, but this is wrong.

They need to break if they encounter empty quotes or other invalid characters, so that skip_invalid_chars() can do its job.

**Comment by BenjaminHThomas** [comment]
fixed
