### ISSUE TITLE
executing a blocking command like "cat" and then pressing ctrl-c displays a double prompt

### ISSUE THREAD

**Issue by BenjaminHThomas** [Haliris/minishell#53]
![image](https://github.com/user-attachments/assets/a683d97b-3664-4a69-8795-2d57988c2ddd)

**Comment by Haliris** [comment]
Same issue as trying to send sigint during the heredoc creation.

The signal handler will just make readline throw a bunch of shit in STDOUT , which gets caught immediately by whichever process is curently reading from the terminal.

**Comment by BenjaminHThomas** [comment]
Same issue with ()

![image](https://github.com/user-attachments/assets/757e451a-4719-4c7e-b69e-ca7dff36d0c2)

**Comment by BenjaminHThomas** [comment]
sigint improvements fixed this
