### ISSUE TITLE
Need to change some error messages

### ISSUE THREAD

**Issue by BenjaminHThomas** [Haliris/minishell#57]
![image](https://github.com/user-attachments/assets/e70447b3-1b29-4cc6-8296-ab25dd3e0ba2)

![image](https://github.com/user-attachments/assets/71f0cfd5-5451-47ae-88e2-32c67e34d6ec)

**Comment by BenjaminHThomas** [comment]
![image](https://github.com/user-attachments/assets/630814cb-c01b-4d4f-b4ca-6c3d16bde049)

![image](https://github.com/user-attachments/assets/762a1c95-5c4d-41b9-a6dd-200271ebd68e)

**Comment by Haliris** [comment]
https://github.com/Haliris/minishell/pull/76/files

**Comment by BenjaminHThomas** [comment]
![image](https://github.com/user-attachments/assets/7db42c76-7f82-46b5-996b-b1fe265af368)

**Comment by Haliris** [comment]
LOL

**Comment by Haliris** [comment]
ft_split() in exec code is bad logic.

I have a plan to refactor the logic to fix the KO.

I am gonna convert the buffer in the command tables the parser builds into a very simple vector.

That way the parser will build a buffer that will keep the NULL bytes in between each words, and have an unsigned int in the vector struct to keep track of size to parse it later.

Then, the ft_split() function will be replaced by a very simple function that will split the buffer based on the null bytes, stopping once it has parsed it in its entirety (thanks to the size int).

The only data I need, is a variable in the lexer nodes that indicates when there is quotes, what they are OR just a simple flag indicating that the string is part of the quotes. That way I can have the parser trim off the limiters from the lexstr buffer before adding it to the vector.

Notes that this is not necessary if the lexer already does the trimming itself.

**Comment by BenjaminHThomas** [comment]
fixed with lexing refactor
